language: python

dist: trusty

matrix:
  include:

# linux + python

    - os: linux
      python: 3.3
      name: ubuntu 14.04 - python@3.3
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.4
      name: ubuntu 14.04 - python@3.4
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.5
      name: ubuntu 14.04 - python@3.5
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.6
      name: ubuntu 14.04 - python@3.6
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 14.04 - python@3.7
      dist: xenial
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8-dev
      name: ubuntu 14.04 - python@3.8-dev
      dist: xenial
      env:
        - MATRIX_EVAL=""

  allow_failures:
    # python2.6 and python3.3 are no longer supported by opencv
    # python3.8 does not yet supports opencv
    - name: ubuntu 14.04 - python@2.6
    - name: ubuntu 14.04 - python@2.7
    - name: ubuntu 14.04 - python@3.3


before_install:
  - travis_retry eval "${MATRIX_EVAL}"
  - pip install pandas
  - pip install sklearn

install:
  - python setup.py install

script:
  #- coverage run tests.py
  - exit 0

after_success:
  - codecov
